---
apiVersion: v1
kind: Service
metadata:
  name: map-api-test
  labels:
    app: map-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: map-api-test
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: map-api-deployment-test
  labels:
    app: map-api
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: map-api-test
    spec:
      containers:
        - image: anthonyamanse/map-api:2.0
          name: map-api
          env:
            - name: MONGODB_URL
              value: ''
          volumeMounts:
            - name: mongodb-cert
              mountPath: "/etc/ssl"
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: mongodb-cert
          secret:
            secretName: mongodb-cert-secret
